---

# renovate: datasource=docker depName=docker.io/envoyproxy/gateway-helm
envoy_gateway_chart_version: "1.8.1"
envoy_gateway_namespace: envoy-gateway-system

# Public gateway IP (assigned by Cilium L2)
gateway_vip: ""

# Gateway class name
gateway_class_name: eg

# Domain for the cluster
cluster_domain: "homelab.local"
