---

- name: Create Traefik dashboard IngressRoute
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: traefik.io/v1alpha1
      kind: IngressRoute
      metadata:
        name: traefik-dashboard
        namespace: "{{ traefik_namespace }}"
      spec:
        entryPoints:
          - websecure
        routes:
          - match: "Host(`{{ traefik_dashboard_hostname }}`)"
            kind: Rule
            services:
              - name: api@internal
                kind: TraefikService
        tls:
          certResolver: letsencrypt
  become: false
  delegate_to: localhost
