---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  sources:
    - repoURL: oci://quay.io/jetstack/charts
      chart: cert-manager
      targetRevision: v1.20.2
      helm:
        valueFiles:
          - $values/kubernetes/platform/cert-manager/app/base/values.yaml
    - repoURL: https://github.com/ngueagho/pi-cluster.git
      targetRevision: roberto
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-webhook-ionos
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  sources:
    - repoURL: https://fabmade.github.io/cert-manager-webhook-ionos
      chart: cert-manager-webhook-ionos
      targetRevision: "1.3.1"
    - repoURL: https://github.com/ngueagho/pi-cluster.git
      targetRevision: roberto
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
