---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: platform
  sources:
    - repoURL: https://kubernetes-sigs.github.io/external-dns
      chart: external-dns
      targetRevision: "1.21.1"
      helm:
        valueFiles:
          - $values/kubernetes/platform/external-dns/app/base/values.yaml
    - repoURL: https://github.com/ngueagho/pi-cluster.git
      targetRevision: roberto
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  project: platform
  sources:
    - repoURL: https://vmware-tanzu.github.io/helm-charts
      chart: velero
      targetRevision: "12.0.3"
      helm:
        valueFiles:
          - $values/kubernetes/platform/velero/app/base/values.yaml
    - repoURL: https://github.com/ngueagho/pi-cluster.git
      targetRevision: roberto
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  namespace: argocd
spec:
  project: platform
  sources:
    - repoURL: https://kubernetes-sigs.github.io/descheduler
      chart: descheduler
      targetRevision: "0.36.0"
    - repoURL: https://github.com/ngueagho/pi-cluster.git
      targetRevision: roberto
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  project: platform
  sources:
    - repoURL: https://kubernetes-sigs.github.io/metrics-server
      chart: metrics-server
      targetRevision: "3.13.1"
    - repoURL: https://github.com/ngueagho/pi-cluster.git
      targetRevision: roberto
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
