---

# renovate: datasource=helm depName=traefik registryUrl=https://helm.traefik.io/traefik
traefik_chart_version: "33.4.0"
traefik_namespace: traefik

# Traefik dashboard
traefik_dashboard_enabled: true
traefik_dashboard_hostname: "traefik.{{ cluster_domain | default('homelab.local') }}"

# Entry points
traefik_web_port: 80
traefik_websecure_port: 443

# Default TLS cert-manager issuer
traefik_tls_issuer: letsencrypt-prod

# Logs
traefik_log_level: INFO
traefik_access_logs: true
